******************************Books Dataset******************************
  library(readr)
books <- read.csv("F:/Excelr/Datasets/book.csv")
View(books)
str(books)
install.packages("arules")
library(arules)
install.packages("arulesViz")
library(arulesViz)
windows()
barplot(sapply(books,sum),col = 1:10)
arules <- apriori(as.matrix(books), parameter = list(support=0.002,confidence=0.6,minlen=2))
arules
inspect(arules[1:5])
plot(arules)
arules_conf <- sort(arules,by="confidence")
inspect(arules_conf[1:5])
arules_lift <- sort(arules,by="lift")
inspect(arules_lift[1:5])
plot(arules,method = "scatterplot")
plot(arules,method = "grouped")
plot(arules,method = "graph")


*******************************Groceries Dataset******************************************
  install.packages("arulesViz")
library("arueslViz")
arules <- apriori(Groceries, parameter = list(support=0.002,confidence=0.6,minlen=2))
arules
inspect(head(sort(arules,by="lift")))
head(quality(arules))
plot(arules)
arules <- apriori(Groceries, parameter = list(support=0.002,confidence=0.6,minlen=2))
arules
inspect(head(sort(arules,by="lift")))
head(quality(arules))
plot(arules)
plot(arules,method = "grouped")
plot(arules[1:20],method = "graph")
write(arules, file="arules.csv",sep=",")
getwd()

********************************My movies Dataset*******************************
  my_movies1 <- read.csv("F:/Excelr/Datasets/my_movies1.csv")
View(my_movies)
str(my_movies)
inspect(my_movies)
install.packages("arules")
library(arules)
install.packages("arulesViz")
library(arulesViz)
windows()
barplot(sapply(my_movies1,sum),col = 1:10)
arules <- apriori(as.matrix(my_movies1), parameter = list(support=0.002,confidence=0.6,minlen=2))
arules
inspect(arules[1:10])
plot(arules,method = "graph")
plot(arules,method = "scatterplot")
plot(arules,method = "grouped")