wine <- read.csv("File.choose()")
View(wine)
normalized_wine <- scale(wine[2:14])
d_wine <- dist(normalized_wine,method = "euclidean")
fit_wine <- hclust(d_wine,method = "complete")
plot(fit_wine, hang = -1)
plot(fit_wine)
rect.hclust(fit_wine, k = 3, border = "red")
groups_wine <- cutree(fit_wine, k =3)
groups_wine
membership_wine <- as.matrix(groups_wine)
final_wine <- data.frame(wine, membership_wine)
View(final_wine)
aggregate(wine[,-1],by=list(final_wine$membership_wine),mean)
install.packages("plyr")
library(plyr)
fit_wine1 <- kmeans(normalized_wine,3)
str(fit_wine1)
fit_wine1$cluster