Startup <- read.csv("F:/Excelr/Datasets/50_Startups.csv")
View(Startup)
summary(Startup)
var(Startup$R.D.Spend)
var(Startup$Marketing.Spend)
var(Startup$Administration)
var(Startup$Profit)
sd(Startup$R.D.Spend)
sd(Startup$Marketing.Spend)
sd(Startup$Administration)
sd(Startup$Profit)
#Measures of skewness
install.packages("moments")
library(moments)
skewness(Startup$R.D.Spend)
skewness(Startup$Administration)
skewness(Startup$Marketing.Spend)
skewness(Startup$Profit)
kurtosis(Startup$R.D.Spend)
kurtosis(Startup$Marketing.Spend)
kurtosis(Startup$Administration)
kurtosis(Startup$Profit)
boxplot(Startup$Profit,horizontal = TRUE)
hist(Startup$Profit)
barplot(Startup$Profit)
str(Startup)
install.packages("psych")
library(psych)
describe(Startup)
# to calculate Z score
qnorm(0.950)#90%
qnorm(0.975)#95%
qnorm(0.995)
qt(0.950,50)
qqnorm(Startup$Profit)
qqline(Startup$Profit)
startup_3 <- Startup[c("R.D.Spend", "Administration", "Marketing.Spend", "Profit")]
plot(Startup)
cor(Startup)
install.packages("corpcor")
library(corpcor)
cor2pcor(cor(Startup))
Profit_Model<-lm(Profit ~. ,data = startup_3)
summary(Profit_Model)
install.packages("car")
library(car)
vif(Profit_Model)
Profit_Model2 <-lm(Profit ~ . ,data = startup_3[-c(50,49,47), ])
summary(Profit_Model2)
vif(Profit_Model2)
influenceIndexPlot(Profit_Model)
install.packages("GGally")
library(GGally)
install.packages("dplyr")
ggpairs(Startup)
avPlots(Profit_Model)
avPlots(Profit_Model2)
startup4 <- Startup[c("R.D.Spend", "Administration", "Profit")]
summary(startup4)
install.packages("MASS")
library(MASS)
stepAIC(Profit_Model)
Profit_Model3 <-lm(Profit ~ . , data = startup4)
summary(Profit_Model3)
plot(Profit_Model3)