book <- read.csv("C:/Users/akritipc/Downloads/book(4).csv")
View(book)
install.packages("recommenderlab",dependencies = TRUE)
library(recommenderlab)
install.packages("matrix")
library(caTools)
str(book)
hist(book$Book.Rating)
book_matrix <- as(book, 'realRatingMatrix')
book_model <- Recommender(book_matrix, method="POPULAR")
recommended_item1 <- predict(book_model, book_matrix[600:605], n=5)
as(recommended_item1, "list")
book_model2 <- Recommender(book_matrix, method="UBCF")
recommended_item2 <- predict(book_model2, book_matrix[600:605], n=5)
as(recommended_item2, "list")